[package]
name = "stm32-download-tool"
version = "0.1.0"
description = "STM32 Serial ISP Download Tool"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
serialport = "4"
thiserror = "2"
chrono = "0.4"
tokio = { version = "1", features = ["sync", "rt"] }
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
